version: "3.8"

services:
    api:
        build: ${BACK_CONTEXT:-.}/deploy/api
        environment:
           - ASPNETCORE_ENVIRONMENT=Development
           - ConnectionStrings__PostgresDataBase=User ID=postgres;Password=password;Server=postgres;Port=5432;Database=olympiad_dev_db;
           - RabbitMqQueueSettings__Uri=amqp://rabbitmq-user:password@rabbitmq:5672
           - S3StorageSettings__ServiceUrl=http://cloudserver-front:8000
        restart: on-failure
        ports:
            - 5501:5501
        depends_on:
            - postgres
            - rabbitmq
            - cloudserver-front
    control-panel:
        build: ${BACK_CONTEXT:-.}/deploy/control-panel
        ports:
            - 5506:5505
        restart: on-failure
    executor:
        build: ${BACK_CONTEXT:-.}/deploy/executor
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - UserInfo__UserName=executor@localhost.ru
            - UserInfo__Password=ExecutorVeryStrongPass1
            - RabbitMqQueueSettings__Uri=amqp://rabbitmq-user:password@rabbitmq:5672
        restart: on-failure
        depends_on:
            - rabbitmq
    postgres:
        image: postgres:13-alpine
        environment:
            - POSTGRES_PASSWORD=password
        ports:
            - 5432:5432
        volumes:
            - ${BACK_CONTEXT:-.}/dev-data/postgres-data/:/var/lib/postgresql/data
        restart: on-failure
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
        
    rabbitmq:
        ports:
            - 5672:5672
            - 8080:15672
        restart: on-failure
        environment:
            - RABBITMQ_DEFAULT_PASS=password
    cloudserver-front:
        image: zenko/cloudserver
        environment:
          REMOTE_MANAGEMENT_DISABLE: '1'
          S3BACKEND: 'file'
          LOG_LEVEL: trace
        ports:
            - 8000:8000
        volumes:
            - ${BACK_CONTEXT:-.}/s3-data/data:/usr/src/app/localData
            - ${BACK_CONTEXT:-.}/s3-data/metadata:/usr/src/app/localMetadata
        restart: on-failure
