version: "3.8"

services:
    api:
        environment:
            - JwtIssuerOptions__SecretKey=${JWT_SECRET_KEY?place jwt secret key! JWT_SECRET_KEY}
            - ConnectionStrings__PostgresDataBase=${POSTGRES_CONNECTION_STRING?pass postgres connection string POSTGRES_CONNECTION_STRING}
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 400M
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    admin:
        environment:
            - JwtIssuerOptions__SecretKey=${JWT_SECRET_KEY?place jwt secret key! JWT_SECRET_KEY}
            - ConnectionStrings__PostgresDataBase=${POSTGRES_CONNECTION_STRING?pass postgres connection string POSTGRES_CONNECTION_STRING}
            - GenerateSettings__Domain=${GENERATE_USER_EMAIL_DOMAIN? Place domain to generate users email GENERATE_USER_EMAIL_DOMAIN}
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.5"
                    memory: 400M
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    results-viewer:
        environment:
            - ConnectionStrings__PostgresDataBase=${POSTGRES_CONNECTION_STRING?pass postgres connection string POSTGRES_CONNECTION_STRING}
            - GeneratePdfOptions__PrintUrl=/results-viewer/pdfprint
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.5"
                    memory: 400M
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    executor:
        environment:
            - StartSettings__PrivateDockerRegistry__Address=${OLYMPIAD_PRIVATE_REGISTRY_ADDRESS?pass olympiad private registry address OLYMPIAD_PRIVATE_REGISTRY_ADDRESS}
            - StartSettings__PrivateDockerRegistry__Login=${OLYMPIAD_PRIVATE_REGISTRY_LOGIN?pass olympiad private registry login OLYMPIAD_PRIVATE_REGISTRY_LOGIN}
            - StartSettings__PrivateDockerRegistry__Password=${OLYMPIAD_PRIVATE_REGISTRY_PASSWORD?pass olympiad private registry password OLYMPIAD_PRIVATE_REGISTRY_PASSWORD}
            - UserInfo__UserName=${EXECUTOR_USER_LOGIN?pass user login for executor service EXECUTOR_USER_LOGIN}
            - UserInfo__Password=${EXECUTOR_USER_PASSWORD?pass user password for executor service EXECUTOR_USER_PASSWORD}
        deploy:
            placement:
                max_replicas_per_node: 1
            resources:
                limits:
                    cpus: "0.5"
                    memory: 500M
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    control-panel:
        deploy:
            resources:
                limits:
                    cpus: '0.1'
                    memory: 50M
                reservations:
                    cpus: '0.05'
                    memory: 20M
        logging:
            driver: json-file
            options:
                max-file: '10'
                max-size: 200k