version: "3.8"

services:
    api:
        environment:
            - JwtIssuerOptions__SecretKey=${JWT_SECRET_KEY?place jwt secret key! JWT_SECRET_KEY}
            - ConnectionStrings__PostgresDataBase=${POSTGRES_CONNECTION_STRING?pass postgres connection string POSTGRES_CONNECTION_STRING}
            - AccountSettings__EmailDomain=${GENERATE_USER_EMAIL_DOMAIN?pass email generating domain GENERATE_USER_EMAIL_DOMAIN}
            - RabbitMqQueueSettings__Uri=amqp://rabbitmq-admin-user:${RABBITMQ_PASSWORD?pass rabbitmq password RABBITMQ_PASSWORD}@rabbitmq:5672
            - S3StorageSettings__ServiceUrl=${S3_SERVICE_URL? Place S3 storage url S3_SERVICE_URL}
            - S3StorageSettings__AccessKeyId=${S3_SERVICE_ACCESS_KEY_ID? Place S3 access key id S3_SERVICE_ACCESS_KEY_ID}
            - S3StorageSettings__SecretAccessKey=${S3_SERVICE_SECRET_ACCESS_KEY? Place S3 access key id S3_SERVICE_SECRET_ACCESS_KEY}
            - S3StorageSettings__ForcePathStyle=${S3_SERVICE_FORCE_PATH_STYLE? Place S3 force path style mode S3_SERVICE_FORCE_PATH_STYLE}
            - S3StorageSettings__BucketName=${S3_SERVICE_BUCKET_NAME? Place S3 bucket name S3_SERVICE_BUCKET_NAME}
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 400M
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    executor:
        environment:
            - StartSettings__PrivateDockerRegistry__Address=${OLYMPIAD_PRIVATE_REGISTRY_ADDRESS?pass olympiad private registry address OLYMPIAD_PRIVATE_REGISTRY_ADDRESS}
            - StartSettings__PrivateDockerRegistry__Login=${OLYMPIAD_PRIVATE_REGISTRY_LOGIN?pass olympiad private registry login OLYMPIAD_PRIVATE_REGISTRY_LOGIN}
            - StartSettings__PrivateDockerRegistry__Password=${OLYMPIAD_PRIVATE_REGISTRY_PASSWORD?pass olympiad private registry password OLYMPIAD_PRIVATE_REGISTRY_PASSWORD}
            - UserInfo__UserName=${EXECUTOR_USER_LOGIN?pass user login for executor service EXECUTOR_USER_LOGIN}
            - UserInfo__Password=${EXECUTOR_USER_PASSWORD?pass user password for executor service EXECUTOR_USER_PASSWORD}
            - RabbitMqQueueSettings__Uri=amqp://rabbitmq-admin-user:${RABBITMQ_PASSWORD?pass rabbitmq password RABBITMQ_PASSWORD}@rabbitmq:5672
        deploy:
            placement:
                max_replicas_per_node: 1
            resources:
                limits:
                    cpus: "0.5"
                    memory: 500M
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    control-panel:
        deploy:
            resources:
                limits:
                    cpus: '0.1'
                    memory: 50M
                reservations:
                    cpus: '0.05'
                    memory: 20M
        logging:
            driver: json-file
            options:
                max-file: '10'
                max-size: 200k
    rabbitmq:
        deploy:
            resources:
                limits:
                    cpus: '0.2'
                    memory: 500M
        logging:
            driver: json-file
            options:
                max-file: '10'
                max-size: 200k
        environment:
            - RABBITMQ_DEFAULT_USER=rabbitmq-admin-user
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD?pass rabbitmq password RABBITMQ_PASSWORD}
